# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mysql-replication-helper}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Scott Tadman}]
  s.date = %q{2011-08-18}
  s.email = %q{github@tadman.ca}
  s.executables = [%q{replication-helper}]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "README.rdoc",
    "Rakefile",
    "bin/replication-helper",
    "lib/mysql_replication_helper.rb",
    "lib/mysql_replication_helper/agent.rb",
    "lib/mysql_replication_helper/agent/master.rb",
    "lib/mysql_replication_helper/agent/slave.rb",
    "lib/mysql_replication_helper/daemon.rb",
    "lib/mysql_replication_helper/daemon_launcher.rb",
    "lib/mysql_replication_helper/error_handler.rb",
    "mysql-replication-helper.gemspec",
    "test/mysql_replication_helper/error_handler_test.rb",
    "test/mysql_replication_helper_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/theworkinggroup/mysql-replication-helper}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.8}
  s.summary = %q{MySQL Replication Helper}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<daemons>, [">= 0"])
    else
      s.add_dependency(%q<daemons>, [">= 0"])
    end
  else
    s.add_dependency(%q<daemons>, [">= 0"])
  end
end

